title: Cabinet of Curiosity 
description: Exploring the data of natural history.
permalink: ':title/'
baseurl: 
url: http://localhost:4000


site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cabinet of Curiosity # add your name
author-img: david-freeman.jpg # add your photo
about-author: Exploring the data of natural history
social-twitter: ofcuriositydata
social-facebook:
social-github:  cabinetofcuriosity
social-linkedin: 
social-email: ofcuriositydata

# Disqus
discus-identifier:  cabinetofcuriosity
comments: true

# Tracker
analytics: UA-116118773-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
